# Generated by Django 6.0.6 on 2026-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('completed', 'Завершен'), ('archived', 'В архиве')], default='completed', max_length=20, verbose_name='Статус')),
                ('technologies', models.TextField(blank=True, verbose_name='Технологии')),
                ('completion_date', models.DateField(verbose_name='Дата завершения')),
                ('project_url', models.URLField(blank=True, verbose_name='Ссылка на проект')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-completion_date'],
            },
        ),
    ]
